--------------------------------------------------------
--  File created - Jumat-November-14-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DATA_SUPIR
--------------------------------------------------------

  CREATE TABLE "HR"."DATA_SUPIR" 
   (	"ID_SUPIR" VARCHAR2(8 BYTE), 
	"NAMA_SUPIR" VARCHAR2(20 BYTE), 
	"NO_TELP" VARCHAR2(20 BYTE), 
	"ALAMAT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.DATA_SUPIR
SET DEFINE OFF;
Insert into HR.DATA_SUPIR (ID_SUPIR,NAMA_SUPIR,NO_TELP,ALAMAT) values ('123','Dion','Jogja',null);
--------------------------------------------------------
--  DDL for Index DATA_SUPIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DATA_SUPIR_PK" ON "HR"."DATA_SUPIR" ("ID_SUPIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DATA_SUPIR
--------------------------------------------------------

  ALTER TABLE "HR"."DATA_SUPIR" ADD CONSTRAINT "DATA_SUPIR_PK" PRIMARY KEY ("ID_SUPIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."DATA_SUPIR" MODIFY ("ID_SUPIR" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DATA_SUPIR" MODIFY ("NAMA_SUPIR" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DATA_SUPIR" MODIFY ("NO_TELP" NOT NULL ENABLE);
